# Generated by Django 3.0.9 on 2020-08-07 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
