# Generated by Django 3.0.9 on 2020-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_lot_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='max_bid',
            field=models.FloatField(default=-1),
        ),
    ]
