# Generated by Django 3.0.9 on 2020-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200807_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='max_bid',
            field=models.FloatField(),
        ),
    ]
