# Generated by Django 3.0.9 on 2020-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200807_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(default='Open', max_length=64),
        ),
    ]
