# Generated by Django 3.0.9 on 2020-08-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200807_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='favourites',
            new_name='watchlist',
        ),
    ]
